# Generated by Django 4.0.4 on 2022-06-29 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnOnline_App', '0002_alter_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
