# Generated by Django 4.0.4 on 2022-07-04 10:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LearnOnline_App', '0004_alter_course_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='favourite',
            field=models.ManyToManyField(blank=True, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
