# Generated by Django 4.0.4 on 2022-07-14 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LearnOnline_App', '0007_quiz'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quiz',
            new_name='Question',
        ),
    ]
