# Generated by Django 4.0.4 on 2022-07-31 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnOnline_App', '0009_remove_course_content_coursefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursefile',
            name='files',
            field=models.FileField(upload_to='course_files/'),
        ),
    ]
